#!/usr/bin/python
import re
import sys
import os
import zipfile
from mechanize import Browser


def add_event_target(form, target):
    #Creates a new __EVENTTARGET control and adds the value specified
    #.NET doesn't generate this in mechanize for some reason -- suspect maybe is 
    #normally generated by javascript or some useragent thing?
    form.new_control('hidden','__EVENTTARGET',attrs = dict(name='__EVENTTARGET'))
    form.set_all_readonly(False)
    form["__EVENTTARGET"] = target


br = Browser()
br.set_handle_robots( False )
br.addheaders = [('User-agent', 'Firefox')]

resp = br.open( "http://www.sptrans.com.br/desenvolvedores/Default.aspx" )

br.select_form( 'frmDev' )
add_event_target(br.form, 'btnDevPlaceLogin')
br.form[ 'devPlaceUserName' ] = sys.argv[1]
br.form[ 'devPlaceUserPass' ] = sys.argv[2]

resp = br.submit()

print resp.info()['Set-Cookie']

br.open( "http://www.sptrans.com.br/desenvolvedores/GTFS.aspx" )
br.select_form( 'frmDev' )
add_event_target(br.form, 'btDownloadGTFS')

resp = br.submit()

#download the gtfs, which happens to be in zip format.
filezip = sys.argv[3]+'.zip'
fileobj = open(filezip, 'w+')
fileobj.write(resp.read())
#unzip it to a folder with name sys.argv[3]
zip = zipfile.ZipFile(filezip)
zip.extractall(sys.argv[3])
#close the descriptor
fileobj.close()
#delete the .zip file
os.remove(filezip)

