#!/usr/bin/python
import re
from mechanize import Browser

def add_event_target(form, target):
    #Creates a new __EVENTTARGET control and adds the value specified
    #.NET doesn't generate this in mechanize for some reason -- suspect maybe is 
    #normally generated by javascript or some useragent thing?
    form.new_control('hidden','__EVENTTARGET',attrs = dict(name='__EVENTTARGET'))
    form.set_all_readonly(False)
    form["__EVENTTARGET"] = target


br = Browser()
br.set_handle_robots( False )
br.addheaders = [('User-agent', 'Firefox')]

resp = br.open( "http://www.sptrans.com.br/desenvolvedores/Default.aspx" )

br.select_form( 'frmDev' )
add_event_target(br.form, 'btnDevPlaceLogin')
br.form[ 'devPlaceUserName' ] = 'ruan0408'
br.form[ 'devPlaceUserPass' ] = 'costaruan'

resp = br.submit()

print resp.info()['Set-Cookie']

br.open( "http://www.sptrans.com.br/desenvolvedores/GTFS.aspx" )
br.select_form( 'frmDev' )
add_event_target(br.form, 'btDownloadGTFS')

resp = br.submit()

fileobj = open('/Users/ruan0408/Downloads/downloadGtfs.zip', 'w+')
fileobj.write(resp.read())
fileobj.close()